const purgeEnabled = process.env.NODE_ENV === "production"

module.exports = {
  purge: {
    enabled: purgeEnabled,
    content: ["./components/**/*.{ts,tsx}", "./pages/**/*.{ts,tsx}"],
  },
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        "normal-type-bg": "#A8A878",
        "normal-type-border": "#6D6D4E",
        "fighting-type-bg": "#C03028",
        "fighting-type-border": "#7D1F1A",
        "flying-type-bg": "#A890F0",
        "flying-type-border": "#6D5E9C",
        "poison-type-bg": "#A040A0",
        "poison-type-border": "#682A68",
        "ground-type-bg": "#E0C068",
        "ground-type-border": "#927D44",
        "rock-type-bg": "#B8A038",
        "rock-type-border": "#786824",
        "bug-type-bg": "#A8B820",
        "bug-type-border": "#6D7815",
        "ghost-type-bg": "#705898",
        "ghost-type-border": "#493963",
        "steel-type-bg": "#B8B8D0",
        "steel-type-border": "#787887",
        "fire-type-bg": "#F08030",
        "fire-type-border": "#9C531F",
        "water-type-bg": "#6890F0",
        "water-type-border": "#445E9C",
        "grass-type-bg": "#78C850",
        "grass-type-border": "#4E8234",
        "electric-type-bg": "#F8D030",
        "electric-type-border": "#A1871F",
        "psychic-type-bg": "#F85888",
        "psychic-type-border": "#A13959",
        "ice-type-bg": "#98D8D8",
        "ice-type-border": "#638D8D",
        "dragon-type-bg": "#7038F8",
        "dragon-type-border": "#4924A1",
        "dark-type-bg": "#705848",
        "dark-type-border": "#49392F",
        "fairy-type-bg": "#EE99AC",
        "fairy-type-border": "#9B6470",
        "hp-stat-bg": "#FF5959",
        "atk-stat-bg": "#F5AC78",
        "def-stat-bg": "#FAE078",
        "sp_atk-stat-bg": "#9DB7F5",
        "sp_def-stat-bg": "#A7DB8D",
        "speed-stat-bg": "#FA92B2",
        "page-alt-color": "#DB2777",
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
